schema_version = "1.0.0"

id = "cadbase_library"
version = "0.2.0"
name = "CADBase Library"
tagline = "Add-on for synchronizing local data with cloud storage"
maintainer = "mnnxp <in@cadbase.rs>"
type = "add-on"
website = "https://app.cadbase.rs/"
tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
[permissions]
network = "Need to to sync library data with a remote server"
files = "Import/export library data from/to disk"