schema_version = "1.0.0"

id = "cadbase_library"
version = "0.1.3"
name = "CADBase Library"
tagline = "This is an addon for synchronizing local data with cloud storage"
maintainer = "mnnxp <in@cadbase.rs>"
type = "add-on"

# Optional link to documentation, support, source files, etc
# website = "http://extensions.blender.org/add-ons/my-example-package/"
website = "https://cadbase.rs/"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/extensions/tags.html
tags = ["Import-Export", "User Interface"]

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/extensions/licenses.html
license = ["SPDX:GPL-2.0-or-later"]

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/extensions/python_wheels.html
wheels = [
    "./wheels/blake3-0.4.1-cp311-cp311-macosx_10_12_x86_64.whl",
    "./wheels/blake3-0.4.1-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/blake3-0.4.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/blake3-0.4.1-cp311-none-win32.whl",
    "./wheels/blake3-0.4.1-cp311-none-win_amd64.whl",
]

# Optional: add-ons can list which resources they will require:
[permissions]
network = "Need to to sync library data with a remote server"
files = "Import/export library data from/to disk"